# Generated by Django 5.0.1 on 2024-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.IntegerField(choices=[(0, 'Army'), (1, 'Tech')], default=0),
        ),
    ]
